version: "3"
services:
  jenkins:
    user: root
    image: jenkins201/jenkins201_jenkins:latest
    hostname: jenkins201_jenkins
    container_name: jenkins201_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
        #- /Users/smccartney/src/jenkins201/jenkins-container/jenkins.yaml:/opt/jenkins/jenkins.yaml
      - ${PWD}/jenkins.yaml:/opt/jenkins/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/opt/jenkins/jenkins.yaml
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}

volumes:
  jenkins_data:
